name: Deploy Backend to VM via Docker

on:
  push:
    branches: 
      - main 
      - develop 
      - 'feature/*'
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.env'
      - 'package.json'
      - 'tsconfig*.json'

  workflow_dispatch:
  
  workflow_run:
    workflows: ["Deploy backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
      CHECKOUT_URL: ${{ secrets.CHECKOUT_URL}}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      CLOUNDINARY_NAME: ${{ secrets.CLOUDINARY_NAME}}
      CLOUNDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY}}
      CLOUNDINARY_API_SECRET: ${{ secrets.CLOUNDINARY_API_SECRET}}


    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Detener contenedor previo (si existe)
        run: |
          docker stop backend || true
          docker rm backend || true

      - name: Creando archivo .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > /tmp/backend.env
          echo "ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}" >> /tmp/backend.env
          echo "CHECKOUT_URL: ${{ secrets.CHECKOUT_URL}}" >> /tmp/backend.env
          echo "JWT_SECRET: ${{ secrets.JWT_SECRET}}" >> /tmp/backend.env
          echo "CLOUNDINARY_NAME: ${{ secrets.CLOUDINARY_NAME}}" >> /tmp/backend.env
          echo "CLOUNDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY}}" >> /tmp/backend.env
          echo "CLOUNDINARY_API_SECRET: ${{ secrets.CLOUNDINARY_API_SECRET}}" >> /tmp/backend.env

      - name: Ejecutar contenedor Docker
        run: |
          docker run -d \
            --name backend \
            --env-file /tmp/backend.env \
            -p 3000:3000 \
            ${{ secrets.ARTIFACT_REGISTRY_URL }}/backend:latest

      - name: Registrar hora del despliegue
        run: |
          echo "Despliegue completado el:"
          date


